In [1]:
import numpy  as np
import h5py
import os

In [2]:
# Will process a txt/.ply/.pcd  file containing xyz coords of points and returns a list of
# numpy arrays of each point. Assumes that the input file is the format that
# CloudCompare exports point files as
def process_pt_file(path):
    data = []
    # Process single point cloud file
    pt_file = open(path, 'r')
    # Pass over header lines
    line='placeholder'
    num_pts=0
    if(path.endswith( '.txt')):  
        header = pt_file.readline()
        num_pts = int(pt_file.readline())
        line = pt_file.readline()
    elif (path.endswith( '.ply')):  
        while line:
            line_list = line.split()
            line = pt_file.readline()
            if('element' in line_list[0] and 'vertex' in line_list[1] ):
                num_pts = int(line_list[2])
            if('end_header' in line_list[0]):
                break
    elif (path.endswith( '.pcd')):
        while line:
            line_list = line.split()
            line = pt_file.readline()
            if('POINTS' in line_list[0]   ):
                num_pts = int(line_list[1])
            if('DATA' in line_list[0] and 'ascii' in line_list[1]):
                break  
    previousEleNum = 0
    currentEleNum = 0
   
    while line:
        line_list = line.split()
        data.append(np.array([float(line_list[0]), float(line_list[1]), float(line_list[2])]))
        line = pt_file.readline()
        previousEleNum=currentEleNum
        currentEleNum=len(line.split())  
        if(currentEleNum>6 or (previousEleNum>0 and currentEleNum != previousEleNum)):
            break
       
       
    # Check number of points
    data = np.array(data)
    checkStr="Number of processed points %d   header number of points %d"%(np.shape(data)[0],num_pts)
    print(checkStr)
    assert num_pts == np.shape(data)[0], checkStr
    return data



In [3]:
import numpy as np
path='2.ply'
x1=process_pt_file(path)
z1= x1-np.mean(x1)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z1))
z1 = z1 / maxABScorrdinateValueofAllpoint
z1 = z1.astype('float32')
z1

Number of processed points 12054   header number of points 12054


array([[ 9.9606194e-18,  5.1062483e-01, -8.4222853e-01],
       [ 9.9606194e-18,  5.3042686e-01, -8.4222853e-01],
       [-7.0010573e-03,  5.1352477e-01, -8.4222853e-01],
       ...,
       [ 2.6026297e-01,  1.6085139e-01,  9.4164008e-01],
       [ 5.2052581e-01,  9.9606194e-18,  8.4222853e-01],
       [ 2.6026297e-01, -1.6085139e-01,  9.4164008e-01]], dtype=float32)

In [4]:
import numpy as np
path='5000_polygon_sphere_100mm.ply'
x2=process_pt_file(path)
z2= x2-np.mean(x2)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z2))
z2 = z2 / maxABScorrdinateValueofAllpoint
z2 = z2.astype('float32')
z2

Number of processed points 4902   header number of points 4902


array([[-0.21478651,  0.00436279,  0.99563724],
       [-0.21478651,  0.05366682,  0.99408776],
       [-0.21788248,  0.05356953,  0.99408776],
       ...,
       [-0.20860733,  0.05327726, -0.5732402 ],
       [-0.21169095,  0.05356873, -0.5732402 ],
       [-0.21478651,  0.00436279, -0.5747897 ]], dtype=float32)

In [5]:
import numpy as np
path='Ball with a surprise_new.ply'
x3=process_pt_file(path)
z3= x3-np.mean(x3)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z3))
z3 = z3 / maxABScorrdinateValueofAllpoint
z3 = z3.astype('float32')
z3

Number of processed points 7588   header number of points 7588


array([[ 0.9824446 ,  0.07166024,  0.00581224],
       [ 0.9824446 ,  0.07033977,  0.01219417],
       [ 0.9856639 , -0.00716804, -0.00716804],
       ...,
       [ 0.6093502 ,  0.03223845, -0.10645124],
       [ 0.5814342 ,  0.02841367, -0.10645124],
       [ 0.57943916,  0.01956734, -0.10645124]], dtype=float32)

In [6]:
import numpy as np
path='sphere12.ply'
x4=process_pt_file(path)
z4= x4-np.mean(x4)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z4))
z4 = z4 / maxABScorrdinateValueofAllpoint
z4 = z4.astype('float32')
z4

Number of processed points 43512   header number of points 43512


array([[-0.05087146,  0.16117962,  0.98538136],
       [-0.03590056,  0.1608619 ,  0.9859234 ],
       [-0.02421434,  0.16333126,  0.9857818 ],
       ...,
       [ 0.03614177, -0.1612415 , -0.9859118 ],
       [ 0.05086181, -0.161239  , -0.9854292 ],
       [ 0.00271945, -0.0027721 , -1.        ]], dtype=float32)

In [7]:
import numpy as np
path='sphrcoewr.ply'
x5=process_pt_file(path)
z5= x5-np.mean(x5)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z5))
z5 = z5 / maxABScorrdinateValueofAllpoint
z5 = z5.astype('float32')
z5

Number of processed points 3649   header number of points 3649


array([[-0.31601742, -0.00561681, -0.05894367],
       [-0.31485325, -0.0147287 , -0.05536112],
       [-0.23347643,  0.02292546,  0.00288068],
       ...,
       [-0.13805947,  0.1762653 ,  0.19318974],
       [-0.17820352,  0.16200416,  0.19933422],
       [-0.1451972 ,  0.13684441,  0.15456429]], dtype=float32)

In [8]:
total_data=np.concatenate((z1, z2,z3,z4,z5), axis=0)

In [9]:
len(total_data)

71705

In [10]:
def make_pt_clouds(total_data, num_clouds, num_pts, filename,randomizePoint=True):
    f = h5py.File(filename, 'w')
   
    if(randomizePoint):
        rand_inds = np.random.randint(np.shape(total_data)[0], size = num_pts)
    else:
        rand_inds=range(num_pts)
    pt_data = np.reshape(total_data[rand_inds, :], (1, num_pts, 3))
    pt_label = np.array([[40]]*num_clouds)
    for i in range(num_clouds - 1):
        rand_inds = np.random.randint(np.shape(total_data)[0], size = num_pts)
        curr_cloud = np.reshape(total_data[rand_inds, :], (1, num_pts, 3))
        pt_data = np.concatenate((pt_data, curr_cloud), axis=0)
    f.create_dataset('data', data=pt_data)
    f.create_dataset('label', data=pt_label)
    f.close()
    print("pt_data shape: ", np.shape(pt_data))


In [11]:
make_pt_clouds(total_data, 1648, 2048, 'ply_data_test2.h5', randomizePoint=True)

pt_data shape:  (1648, 2048, 3)


In [12]:
import h5py
filename = 'ply_data_test2.h5'
f = h5py.File(filename, 'r')

# List all groups
print("Keys: %s" % f.keys())
a_group_key = list(f.keys())[0]
b_group_key = list(f.keys())[1]
# Get the data
data = list(f[a_group_key])
label = list(f[b_group_key])

Keys: KeysView(<HDF5 file "ply_data_test2.h5" (mode r)>)


In [13]:
list(f.keys())

['data', 'label']

In [14]:
dset = f['data']

In [15]:
dset.shape

(1648, 2048, 3)

In [16]:
data

[array([[-0.287433  ,  0.20727792, -0.9349032 ],
        [-0.474298  ,  0.6805338 , -0.5580104 ],
        [ 0.9819895 , -0.16629295,  0.08482864],
        ...,
        [ 0.05520673,  0.91481566, -0.39948547],
        [-0.59273267,  0.32625493,  0.26889268],
        [ 0.5210934 ,  0.64779156,  0.555022  ]], dtype=float32),
 array([[-0.03860557, -0.969724  , -0.24148121],
        [ 0.7091752 ,  0.14628614,  0.6745934 ],
        [ 0.5205258 ,  0.00700106, -0.8492296 ],
        ...,
        [-0.52528876, -0.14784685, -0.837787  ],
        [-0.9777558 , -0.18302196,  0.10062925],
        [-0.26037753, -0.16055217, -0.9412628 ]], dtype=float32),
 array([[ 0.25491962, -0.03735932,  0.96584904],
        [-0.981831  , -0.05306275,  0.18106878],
        [-0.19568545,  0.9636053 , -0.18081193],
        ...,
        [ 0.19647975, -0.66248447, -0.72246647],
        [ 0.49236968, -0.20735781, -0.84494436],
        [ 0.38241875,  0.5090045 , -0.7708475 ]], dtype=float32),
 array([[-0.85338736,  0.117