In [31]:
import numpy  as np
import h5py
import os

In [32]:
# Will process a txt/.ply/.pcd  file containing xyz coords of points and returns a list of
# numpy arrays of each point. Assumes that the input file is the format that
# CloudCompare exports point files as
def process_pt_file(path):
    data = []
    # Process single point cloud file
    pt_file = open(path, 'r')
    # Pass over header lines
    line='placeholder'
    num_pts=0
    if(path.endswith( '.txt')):  
        header = pt_file.readline()
        num_pts = int(pt_file.readline())
        line = pt_file.readline()
    elif (path.endswith( '.ply')):  
        while line:
            line_list = line.split()
            line = pt_file.readline()
            if('element' in line_list[0] and 'vertex' in line_list[1] ):
                num_pts = int(line_list[2])
            if('end_header' in line_list[0]):
                break
    elif (path.endswith( '.pcd')):
        while line:
            line_list = line.split()
            line = pt_file.readline()
            if('POINTS' in line_list[0]   ):
                num_pts = int(line_list[1])
            if('DATA' in line_list[0] and 'ascii' in line_list[1]):
                break  
    previousEleNum = 0
    currentEleNum = 0
   
    while line:
        line_list = line.split()
        data.append(np.array([float(line_list[0]), float(line_list[1]), float(line_list[2])]))
        line = pt_file.readline()
        previousEleNum=currentEleNum
        currentEleNum=len(line.split())  
        if(currentEleNum>6 or (previousEleNum>0 and currentEleNum != previousEleNum)):
            break
       
       
    # Check number of points
    data = np.array(data)
    checkStr="Number of processed points %d   header number of points %d"%(np.shape(data)[0],num_pts)
    print(checkStr)
    assert num_pts == np.shape(data)[0], checkStr
    return data



In [33]:
path='Ball OBJ.ply'

In [34]:
process_pt_file(path)

Number of processed points 16292   header number of points 16292


array([[ 0.816137,  0.311737, -0.385328],
       [ 0.93521 ,  0.      , -0.192664],
       [ 0.816137, -0.311737, -0.385328],
       ...,
       [-0.11171 ,  0.741312, -0.614549],
       [-0.133702,  0.739381, -0.612949],
       [-0.155509,  0.737121, -0.611075]])

In [35]:
x14=process_pt_file(path)

Number of processed points 16292   header number of points 16292


In [36]:
import numpy as np
z14= x14-np.mean(x14)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z14))
z14 = z14 / maxABScorrdinateValueofAllpoint
z14 = z14.astype('float32')
z14

array([[ 8.4309930e-01,  3.2203570e-01, -3.9805788e-01],
       [ 9.6610606e-01, -1.5429181e-09, -1.9902895e-01],
       [ 8.4309930e-01, -3.2203570e-01, -3.9805788e-01],
       ...,
       [-1.1540051e-01,  7.6580238e-01, -6.3485157e-01],
       [-1.3811904e-01,  7.6380754e-01, -6.3319868e-01],
       [-1.6064647e-01,  7.6147288e-01, -6.3126278e-01]], dtype=float32)

In [37]:
import numpy as np
path='ccosprwr_new.ply'
x1=process_pt_file(path)
z1= x1-np.mean(x1)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z1))
z1 = z1 / maxABScorrdinateValueofAllpoint
z1 = z1.astype('float32')
z1

Number of processed points 8808   header number of points 8808


array([[-0.18793084, -0.48582414,  0.13117158],
       [-0.05782631, -0.46998942,  0.13759874],
       [-0.05057272, -0.47240236,  0.14349194],
       ...,
       [-0.36207488, -0.699672  ,  0.3138972 ],
       [-0.3812672 , -0.53561646,  0.19842187],
       [-0.38178685, -0.5445686 ,  0.21215041]], dtype=float32)

In [38]:
import numpy as np
path='glassball.ply'
x2=process_pt_file(path)
z2= x2-np.mean(x2)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z2))
z2 = z2 / maxABScorrdinateValueofAllpoint
z2 = z2.astype('float32')
z2

Number of processed points 63492   header number of points 63492


array([[ 6.1517384e-02, -7.6960373e-01, -6.2458992e-01],
       [ 4.6170868e-02, -7.6960373e-01, -6.2591261e-01],
       [ 3.0794840e-02, -7.6960373e-01, -6.2685698e-01],
       ...,
       [-1.4193998e-07, -6.8916333e-01, -6.8463182e-01],
       [-1.4193998e-07, -9.0039253e-01, -3.7050045e-01],
       [-1.4193998e-07, -9.5519727e-01, -1.9557163e-01]], dtype=float32)

In [39]:
import numpy as np
path='globe-sphere.ply'
x3=process_pt_file(path)
z3= x3-np.mean(x3)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z3))
z3 = z3 / maxABScorrdinateValueofAllpoint
z3 = z3.astype('float32')
z3

Number of processed points 16022   header number of points 16022


array([[ 0.046048  , -0.00198374,  0.99844575],
       [ 0.04015228, -0.00319946,  0.9986456 ],
       [ 0.07051464, -0.00532292,  0.9969718 ],
       ...,
       [ 0.10388941,  0.00326245, -0.99240935],
       [ 0.07211668,  0.00212568, -0.9953822 ],
       [ 0.046048  ,  0.00121394, -0.99690604]], dtype=float32)

In [40]:
import numpy as np
path='magic-sphere.ply'
x4=process_pt_file(path)
z4= x4-np.mean(x4)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z4))
z4 = z4 / maxABScorrdinateValueofAllpoint
z4 = z4.astype('float32')
z4

Number of processed points 33007   header number of points 33007


array([[ 0.02498175,  0.02171218,  0.01699514],
       [ 0.34030944,  0.8424251 ,  0.4378481 ],
       [ 0.21442021,  0.93044937,  0.31778815],
       ...,
       [-0.04657668, -0.94957286, -0.18286742],
       [ 0.61423033, -0.58425176,  0.5176077 ],
       [ 0.4193445 , -0.7535536 ,  0.48109215]], dtype=float32)

In [41]:
import numpy as np
path='math_form_1_stl.ply'
x5=process_pt_file(path)
z5= x5-np.mean(x5)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z5))
z5 = z5 / maxABScorrdinateValueofAllpoint
z5 = z5.astype('float32')
z5

Number of processed points 91920   header number of points 91920


array([[-0.15286168, -0.60648966,  0.62171674],
       [-0.15122475, -0.6049146 ,  0.6222939 ],
       [-0.15132032, -0.6041731 ,  0.6210545 ],
       ...,
       [-0.27686965, -0.56871897,  0.5977581 ],
       [-0.26965624, -0.5688605 ,  0.5957296 ],
       [-0.26259094, -0.5691449 ,  0.59375703]], dtype=float32)

In [42]:
import numpy as np
path='ocm-sphere.ply'
x6=process_pt_file(path)
z6= x6-np.mean(x6)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z6))
z6 = z6 / maxABScorrdinateValueofAllpoint
z6 = z6.astype('float32')
z6

Number of processed points 16022   header number of points 16022


array([[-0.        ,  1.        , -0.        ],
       [ 0.07115513,  0.99696785, -0.        ],
       [ 0.13903211,  0.98966753, -0.        ],
       ...,
       [ 0.20757113, -0.977619  , -0.00728832],
       [ 0.13893211, -0.98966753, -0.00488822],
       [ 0.0725572 , -0.99691784, -0.00251211]], dtype=float32)

In [43]:
import numpy as np
path='only_quad_sphere.ply'
x7=process_pt_file(path)
z7= x7-np.mean(x7)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z7))
z7 = z7 / maxABScorrdinateValueofAllpoint
z7 = z7.astype('float32')
z7

Number of processed points 3076   header number of points 3076


array([[ 0.6421479 ,  0.74498516,  0.17420371],
       [ 0.65981555,  0.74813604,  0.05137581],
       [ 0.66721845,  0.7401521 , -0.06854298],
       ...,
       [-0.69521695, -0.00677827, -0.71879643],
       [-0.90610516, -0.0897651 ,  0.41346985],
       [-0.04713966, -0.8544636 ,  0.517408  ]], dtype=float32)

In [44]:
import numpy as np
path='Golf+ball.ply'
x8=process_pt_file(path)
z8= x8-np.mean(x8)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z8))
z8 = z8 / maxABScorrdinateValueofAllpoint
z8 = z8.astype('float32')
z8

Number of processed points 482   header number of points 482


array([[ 0.8228681 , -0.5709544 , -0.39831617],
       [ 0.81364053, -0.5665785 , -0.3822848 ],
       [ 0.81397885, -0.56304693, -0.3835996 ],
       ...,
       [ 0.97108394, -0.54957736, -0.2755152 ],
       [ 0.9705976 , -0.5458696 , -0.27564922],
       [ 0.9828237 , -0.54607683, -0.2903446 ]], dtype=float32)

In [45]:
import numpy as np
path='sphere_meshmix.ply'
x9=process_pt_file(path)
z9= x9-np.mean(x9)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z9))
z9 = z9 / maxABScorrdinateValueofAllpoint
z9 = z9.astype('float32')
z9

Number of processed points 9471   header number of points 9471


array([[-0.84046346, -0.01788121, -0.4647207 ],
       [-0.8378975 ,  0.01170316,  0.51639444],
       [-0.05858253, -0.447163  ,  0.8364638 ],
       ...,
       [-0.3301504 , -0.3491369 , -0.86040944],
       [-0.30885768, -0.45774478, -0.81570435],
       [-0.33263347, -0.32710788, -0.8683304 ]], dtype=float32)

In [46]:
import numpy as np
path='sphere_meshmix_2_new.ply'
x10=process_pt_file(path)
z10= x10-np.mean(x10)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z10))
z10 = z10 / maxABScorrdinateValueofAllpoint
z10 = z10.astype('float32')
z10

Number of processed points 56814   header number of points 56814


array([[ 0.43420705,  0.09319674, -0.71443784],
       [ 0.41877395,  0.12290815, -0.7058714 ],
       [ 0.402057  ,  0.08939344, -0.7287626 ],
       ...,
       [ 0.5697889 ,  0.7584276 , -0.24726321],
       [ 0.55300844,  0.77821416, -0.23798348],
       [ 0.5486565 ,  0.74698573, -0.27111116]], dtype=float32)

In [47]:
import numpy as np
path='sphere_new.ply'
x11=process_pt_file(path)
z11= x11-np.mean(x11)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z11))
z11 = z11 / maxABScorrdinateValueofAllpoint
z11 = z11.astype('float32')
z11

Number of processed points 2280   header number of points 2280


array([[-0.11609054,  0.03681943, -0.9778926 ],
       [-0.09450281,  0.07918762, -0.9778926 ],
       [-0.21443237,  0.16632137, -0.9423031 ],
       ...,
       [-0.12352902, -0.010146  ,  0.9412759 ],
       [-0.11609054,  0.03681934,  0.9412759 ],
       [ 0.02845422, -0.010146  ,  0.9532373 ]], dtype=float32)

In [48]:
import numpy as np
path='webtrcc.ply'
x12=process_pt_file(path)
z12= x12-np.mean(x12)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z12))
z12 = z12 / maxABScorrdinateValueofAllpoint
z12 = z12.astype('float32')
z12

Number of processed points 1718   header number of points 1718


array([[-0.35513887,  0.7477807 ,  0.21573453],
       [-0.50039583,  0.70371747,  0.21573453],
       [-0.6342641 ,  0.632163  ,  0.21573453],
       ...,
       [-0.48804006,  0.6989562 ,  0.32263267],
       [-0.5073329 ,  0.6989562 ,  0.22564112],
       [-0.6233858 ,  0.6369242 ,  0.22564112]], dtype=float32)

In [49]:
import numpy as np
path='Wire_Sphere_5.ply'
x13=process_pt_file(path)
z13= x13-np.mean(x13)
maxABScorrdinateValueofAllpoint = np.max(np.absolute(z13))
z13 = z13 / maxABScorrdinateValueofAllpoint
z13 = z13.astype('float32')
z13

Number of processed points 13387   header number of points 13387


array([[ 0.00177956, -0.00261614, -0.9968484 ],
       [ 0.04598663,  0.02584545, -0.9955169 ],
       [ 0.07637452, -0.02694515, -0.9792584 ],
       ...,
       [-0.12054312,  0.03739752, -0.8767273 ],
       [-0.10874525,  0.02377715, -0.9371216 ],
       [-0.07484248, -0.00682282, -0.98059   ]], dtype=float32)

In [50]:
total_data=np.concatenate((z1, z2,z3,z4,z5,z6,z7,z8,z9,z10,z11,z12,z13,z14), axis=0)

In [51]:
len(total_data)

332791

In [52]:
def make_pt_clouds(total_data, num_clouds, num_pts, filename,randomizePoint=True):
    f = h5py.File(filename, 'w')
   
    if(randomizePoint):
        rand_inds = np.random.randint(np.shape(total_data)[0], size = num_pts)
    else:
        rand_inds=range(num_pts)
    pt_data = np.reshape(total_data[rand_inds, :], (1, num_pts, 3))
    pt_label = np.array([[40]]*num_clouds)
    for i in range(num_clouds - 1):
        rand_inds = np.random.randint(np.shape(total_data)[0], size = num_pts)
        curr_cloud = np.reshape(total_data[rand_inds, :], (1, num_pts, 3))
        pt_data = np.concatenate((pt_data, curr_cloud), axis=0)
    f.create_dataset('data', data=pt_data)
    f.create_dataset('label', data=pt_label)
    f.close()
    print("pt_data shape: ", np.shape(pt_data))

In [53]:
make_pt_clouds(total_data, 1648, 2048, 'ply_data_train5.h5', randomizePoint=True)

pt_data shape:  (1648, 2048, 3)


In [54]:
import h5py
filename = 'ply_data_train5.h5'
f = h5py.File(filename, 'r')

# List all groups
print("Keys: %s" % f.keys())
a_group_key = list(f.keys())[0]

# Get the data
data = list(f[a_group_key])

Keys: KeysView(<HDF5 file "ply_data_train5.h5" (mode r)>)


In [55]:
list(f.keys())

['data', 'label']

In [56]:
dset = f['data']

In [57]:
dset.shape

(1648, 2048, 3)

In [58]:
data

[array([[ 0.28231192,  0.8844389 , -0.36323643],
        [ 0.40854517,  0.3431347 ,  0.8353083 ],
        [ 0.4311037 ,  0.3127735 , -0.8474887 ],
        ...,
        [-0.0380128 , -0.57261884,  0.85825247],
        [ 0.5701751 ,  0.78753465,  0.23031013],
        [-0.20734733, -0.7419774 ,  0.69084096]], dtype=float32),
 array([[-0.4643932 , -0.8359318 ,  0.17913555],
        [-0.13904741, -0.6574274 ,  0.6377587 ],
        [-0.15994525, -0.71870995,  0.8979151 ],
        ...,
        [-0.00461215, -0.9935207 ,  0.07975344],
        [-0.44169682,  0.46198118,  0.7414112 ],
        [ 0.14915417,  0.8086303 , -0.3422203 ]], dtype=float32),
 array([[-0.850841  , -0.2852412 , -0.35116443],
        [ 0.12300003,  0.9709433 , -0.18408051],
        [ 0.17208992,  0.5304172 , -0.8271293 ],
        ...,
        [-0.16550289, -0.4102621 ,  0.69960856],
        [-0.1478071 , -0.4099498 ,  0.87867093],
        [ 0.12358224,  0.85395026,  0.49336886]], dtype=float32),
 array([[-0.1031196 ,  0.966