In [3]:
import numpy  as np
import h5py
import os

In [4]:
# Will process a txt/.ply/.pcd  file containing xyz coords of points and returns a list of
# numpy arrays of each point. Assumes that the input file is the format that
# CloudCompare exports point files as
def process_pt_file(path):
    data = []
    # Process single point cloud file
    pt_file = open(path, 'r')
    # Pass over header lines
    line='placeholder'
    num_pts=0
    if(path.endswith( '.txt')):  
        header = pt_file.readline()
        num_pts = int(pt_file.readline())
        line = pt_file.readline()
    elif (path.endswith( '.ply')):  
        while line:
            line_list = line.split()
            line = pt_file.readline()
            if('element' in line_list[0] and 'vertex' in line_list[1] ):
                num_pts = int(line_list[2])
            if('end_header' in line_list[0]):
                break
    elif (path.endswith( '.pcd')):
        while line:
            line_list = line.split()
            line = pt_file.readline()
            if('POINTS' in line_list[0]   ):
                num_pts = int(line_list[1])
            if('DATA' in line_list[0] and 'ascii' in line_list[1]):
                break  
    previousEleNum = 0
    currentEleNum = 0
   
    while line:
        line_list = line.split()
        data.append(np.array([float(line_list[0]), float(line_list[1]), float(line_list[2])]))
        line = pt_file.readline()
        previousEleNum=currentEleNum
        currentEleNum=len(line.split())  
        if(currentEleNum>6 or (previousEleNum>0 and currentEleNum != previousEleNum)):
            break
       
       
    # Check number of points
    data = np.array(data)
    checkStr="Number of processed points %d   header number of points %d"%(np.shape(data)[0],num_pts)
    print(checkStr)
    assert num_pts == np.shape(data)[0], checkStr
    return data



In [5]:
path='Ball OBJ.ply'

In [6]:
process_pt_file(path)

Number of processed points 16292   header number of points 16292


array([[ 0.816137,  0.311737, -0.385328],
       [ 0.93521 ,  0.      , -0.192664],
       [ 0.816137, -0.311737, -0.385328],
       ...,
       [-0.11171 ,  0.741312, -0.614549],
       [-0.133702,  0.739381, -0.612949],
       [-0.155509,  0.737121, -0.611075]])

In [11]:
x14=process_pt_file(path)

Number of processed points 16292   header number of points 16292


In [14]:
import numpy as np
from sklearn.preprocessing import normalize


z14 = normalize(x14)
z14 = z14.astype('float32')
z14

array([[ 0.8547286 ,  0.32647768, -0.40354848],
       [ 0.97943205,  0.        , -0.20177425],
       [ 0.8547286 , -0.32647768, -0.40354848],
       ...,
       [-0.11523888,  0.7647298 , -0.6339624 ],
       [-0.1378835 ,  0.762505  , -0.6321189 ],
       [-0.16031489,  0.75990117, -0.6299598 ]], dtype=float32)

In [22]:
import numpy as np
from sklearn.preprocessing import normalize
path='ccosprwr_new.ply'
x1=process_pt_file(path)
z1 = normalize(x1)
z1 = z1.astype('float32')
z1

Number of processed points 8808   header number of points 8808


array([[-0.05064618, -0.7320938 ,  0.6793185 ],
       [ 0.24371915, -0.68669677,  0.68487114],
       [ 0.25576177, -0.68061674,  0.686547  ],
       ...,
       [-0.26379362, -0.7175036 ,  0.6446717 ],
       [-0.38340482, -0.6580443 ,  0.64805746],
       [-0.37432194, -0.6564235 ,  0.6549743 ]], dtype=float32)

In [23]:
import numpy as np
from sklearn.preprocessing import normalize
path='glassball.ply'
x2=process_pt_file(path)
z2 = normalize(x2)
z2 = z2.astype('float32')
z2

Number of processed points 63492   header number of points 63492


array([[ 0.06194687, -0.77497476, -0.62894887],
       [ 0.04649321, -0.7749742 , -0.6302804 ],
       [ 0.03100989, -0.77497435, -0.6312314 ],
       ...,
       [ 0.        , -0.70943534, -0.7047705 ],
       [ 0.        , -0.92476827, -0.3805307 ],
       [ 0.        , -0.9796766 , -0.20058352]], dtype=float32)

In [27]:
import numpy as np
from sklearn.preprocessing import normalize
path='globe-sphere.ply'
x3=process_pt_file(path)
z3 = normalize(x3)
z3 = z3.astype('float32')
z3

Number of processed points 16022   header number of points 16022


array([[0.42389712, 0.4044042 , 0.8104125 ],
       [0.4219879 , 0.40437412, 0.8114233 ],
       [0.43243346, 0.4017548 , 0.80721396],
       ...,
       [0.7400721 , 0.6725153 , 0.00406249],
       [0.7305834 , 0.6828202 , 0.00210069],
       [0.72244126, 0.69143146, 0.00107512]], dtype=float32)

In [28]:
import numpy as np
from sklearn.preprocessing import normalize
path='magic-sphere.ply'
x4=process_pt_file(path)
z4 = normalize(x4)
z4 = z4.astype('float32')
z4

Number of processed points 33007   header number of points 33007


array([[0.5795295 , 0.5776278 , 0.57488406],
       [0.49590006, 0.6857349 , 0.5327765 ],
       [0.4586248 , 0.7355655 , 0.49860474],
       ...,
       [0.7608313 , 0.01791869, 0.64870226],
       [0.7176918 , 0.17521577, 0.67395693],
       [0.6875655 , 0.1076806 , 0.71809375]], dtype=float32)

In [29]:
import numpy as np
from sklearn.preprocessing import normalize
path='math_form_1_stl.ply'
x5=process_pt_file(path)
z5 = normalize(x5)
z5 = z5.astype('float32')
z5

Number of processed points 91920   header number of points 91920


array([[ 0.08124848, -0.40461546,  0.9108705 ],
       [ 0.08299957, -0.40291798,  0.91146487],
       [ 0.08302494, -0.4027434 ,  0.9115397 ],
       ...,
       [-0.05380046, -0.37989753,  0.9234627 ],
       [-0.04585217, -0.38098314,  0.92344433],
       [-0.03802409, -0.3821618 ,  0.9233128 ]], dtype=float32)

In [30]:
import numpy as np
from sklearn.preprocessing import normalize
path='ocm-sphere.ply'
x6=process_pt_file(path)
z6 = normalize(x6)
z6 = z6.astype('float32')
z6

Number of processed points 16022   header number of points 16022


array([[-0.        ,  1.        , -0.        ],
       [ 0.07119045,  0.99746275, -0.        ],
       [ 0.13911758,  0.99027586, -0.        ],
       ...,
       [ 0.20768769, -0.978168  , -0.00729241],
       [ 0.13901778, -0.9902778 , -0.00489123],
       [ 0.07258928, -0.99735874, -0.00251322]], dtype=float32)

In [31]:
import numpy as np
from sklearn.preprocessing import normalize
path='only_quad_sphere.ply'
x7=process_pt_file(path)
z7 = normalize(x7)
z7 = z7.astype('float32')
z7

Number of processed points 3076   header number of points 3076


array([[ 0.6428864 ,  0.745842  ,  0.17440407],
       [ 0.6605745 ,  0.74899656,  0.0514349 ],
       [ 0.66798586,  0.74100333, -0.06862181],
       ...,
       [-0.69520277, -0.00677813, -0.7187817 ],
       [-0.90608627, -0.08976322,  0.41346124],
       [-0.04713868, -0.854446  ,  0.51739734]], dtype=float32)

In [32]:
import numpy as np
from sklearn.preprocessing import normalize
path='Golf+ball.ply'
x8=process_pt_file(path)
z8 = normalize(x8)
z8 = z8.astype('float32')
z8

Number of processed points 482   header number of points 482


array([[0.98358655, 0.05652852, 0.17135352],
       [0.98134804, 0.0596761 , 0.18274234],
       [0.98137265, 0.0620217 , 0.18182704],
       ...,
       [0.9717696 , 0.06352953, 0.22721766],
       [0.97163194, 0.06575438, 0.22717334],
       [0.9739237 , 0.06529458, 0.21727684]], dtype=float32)

In [33]:
import numpy as np
from sklearn.preprocessing import normalize
path='sphere_meshmix.ply'
x9=process_pt_file(path)
z9 = normalize(x9)
z9 = z9.astype('float32')
z9

Number of processed points 9471   header number of points 9471


array([[-0.8736161 , -0.02498369, -0.485974  ],
       [-0.85590225,  0.00544179,  0.51710904],
       [-0.06846818, -0.47829837,  0.8755243 ],
       ...,
       [-0.33803937, -0.35711354, -0.87074643],
       [-0.31670645, -0.46630836, -0.8259864 ],
       [-0.34048328, -0.334933  , -0.8785733 ]], dtype=float32)

In [34]:
import numpy as np
from sklearn.preprocessing import normalize
path='sphere_meshmix_2_new.ply'
x10=process_pt_file(path)
z10 = normalize(x10)
z10 = z10.astype('float32')
z10

Number of processed points 56814   header number of points 56814


array([[ 0.4244399 ,  0.02976496, -0.9049668 ],
       [ 0.41270274,  0.06511841, -0.9085351 ],
       [ 0.3872619 ,  0.02536519, -0.9216208 ],
       ...,
       [ 0.5517598 ,  0.75896907, -0.34572697],
       [ 0.5315975 ,  0.7781712 , -0.33444536],
       [ 0.5353346 ,  0.75598603, -0.37669885]], dtype=float32)

In [35]:
import numpy as np
from sklearn.preprocessing import normalize
path='sphere_new.ply'
x11=process_pt_file(path)
z11 = normalize(x11)
z11 = z11.astype('float32')
z11

Number of processed points 2280   header number of points 2280


array([[-0.10121045,  0.05706055, -0.99322736],
       [-0.07875159,  0.10076796, -0.99178827],
       [-0.20377482,  0.1918321 , -0.96003973],
       ...,
       [-0.10899515,  0.00845514,  0.99400634],
       [-0.10121045,  0.05706045,  0.99322736],
       [ 0.04807478,  0.00839139,  0.9988085 ]], dtype=float32)

In [36]:
import numpy as np
from sklearn.preprocessing import normalize
path='webtrcc.ply'
x12=process_pt_file(path)
z12 = normalize(x12)
z12 = z12.astype('float32')
z12

Number of processed points 1718   header number of points 1718


array([[-0.48035342,  0.85177106,  0.20915696],
       [-0.62203497,  0.7574393 ,  0.198389  ],
       [-0.74037373,  0.64495265,  0.1894276 ],
       ...,
       [-0.5966644 ,  0.73811054,  0.31493548],
       [-0.627992  ,  0.7496088 ,  0.2090757 ],
       [-0.7308571 ,  0.6522878 ,  0.20091939]], dtype=float32)

In [37]:
import numpy as np
from sklearn.preprocessing import normalize
path='Wire_Sphere_5.ply'
x13=process_pt_file(path)
z13 = normalize(x13)
z13 = z13.astype('float32')
z13

Number of processed points 13387   header number of points 13387


array([[ 0.00124601, -0.00316118, -0.9999942 ],
       [ 0.0455678 ,  0.02537434, -0.9986389 ],
       [ 0.07714063, -0.0279541 , -0.9966283 ],
       ...,
       [-0.13660553,  0.04158722, -0.98975223],
       [-0.11572918,  0.02461143, -0.99297583],
       [-0.0766014 , -0.00747894, -0.9970338 ]], dtype=float32)

In [38]:
total_data=np.concatenate((z1, z2,z3,z4,z5,z6,z7,z8,z9,z10,z11,z12,z13,z14), axis=0)

In [39]:
len(total_data)

332791

In [40]:
def make_pt_clouds(total_data, num_clouds, num_pts, filename,randomizePoint=True):
    f = h5py.File(filename, 'w')
   
    if(randomizePoint):
        rand_inds = np.random.randint(np.shape(total_data)[0], size = num_pts)
    else:
        rand_inds=range(num_pts)
    pt_data = np.reshape(total_data[rand_inds, :], (1, num_pts, 3))
    pt_label = np.array([[40]]*num_clouds)
    for i in range(num_clouds - 1):
        rand_inds = np.random.randint(np.shape(total_data)[0], size = num_pts)
        curr_cloud = np.reshape(total_data[rand_inds, :], (1, num_pts, 3))
        pt_data = np.concatenate((pt_data, curr_cloud), axis=0)
    f.create_dataset('data', data=pt_data)
    f.create_dataset('label', data=pt_label)
    f.close()
    print("pt_data shape: ", np.shape(pt_data))

In [41]:
make_pt_clouds(total_data, 1648, 2048, 'ply_data_train5.h5', randomizePoint=True)

pt_data shape:  (1648, 2048, 3)


In [17]:
import h5py
filename = 'ply_data_train5.h5'
f = h5py.File(filename, 'r')

# List all groups
print("Keys: %s" % f.keys())
a_group_key = list(f.keys())[0]

# Get the data
data = list(f[a_group_key])

Keys: KeysView(<HDF5 file "c.h5" (mode r)>)


In [18]:
list(f.keys())

['data', 'label']

In [19]:
dset = f['data']

In [20]:
dset.shape

(1648, 2048, 3)

In [21]:
data

[array([[-0.        ,  0.9717588 ,  0.2359764 ],
        [-0.32189617,  0.9377098 , -0.13070267],
        [-0.05566034,  0.27399087,  0.96012026],
        ...,
        [ 0.5876615 , -0.6772419 , -0.44271588],
        [ 0.69448245, -0.22511867,  0.6833855 ],
        [ 0.73045045,  0.38022742, -0.5673352 ]], dtype=float32),
 array([[-0.63548344,  0.09241234,  0.76656425],
        [-0.3915656 , -0.33419168, -0.8573169 ],
        [ 0.7772234 , -0.43319133, -0.456365  ],
        ...,
        [ 0.33396244, -0.6779953 ,  0.6548217 ],
        [-0.11523782,  0.9926377 , -0.03729196],
        [-0.6557622 ,  0.18012585,  0.7331648 ]], dtype=float32),
 array([[-0.16773771,  0.9579905 , -0.23263311],
        [-0.9303029 ,  0.07570262, -0.35889494],
        [-0.73271155, -0.02341297, -0.68013644],
        ...,
        [-0.4109418 , -0.6627491 ,  0.62601155],
        [-0.69448245, -0.22511867,  0.6833855 ],
        [-0.24869645, -0.92495173, -0.2874272 ]], dtype=float32),
 array([[ 0.8573169 , -0.391